name: Playwright Tests
on:
  repository_dispatch:
      types: [trigger-e2e-tests]
  push:
    branches: [ main, master, CI_testing ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    # - name: Clone Cryptpad
    - uses: actions/checkout@main
    - name: SSH-test-2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      run: ${{secrets.SSH}}
      # with:
      #   name: cryptpad/cryptpad    
          # ref: refs/heads/release
    # - name: Clone cryptpad 
    #   run: git@github.com:cryptpad/cryptpad.git
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test anon --project='chrome' --workers=2
      env: 
        PW_URL: ${{ secrets.PW_URL }}
        MY_SECRET_2: ${{ secrets.MY_SECRET_2 }}
        MY_SECRET_3: ${{ secrets.MY_SECRET_3 }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30